### ISSUE TITLE
Cannot read property 'query' of null

### ISSUE THREAD

**Issue by emroot** [nandorojo/expo-next-react-navigation#10]
I keep getting the this error when tryin to use `useRouting` on web.
![image](https://user-images.githubusercontent.com/110190/76690165-bc15dc00-65fa-11ea-918c-d9762ed8c9b3.png)

This is my index.tsx page
``` javascript
// @generated: @expo/next-adapter@2.0.10
import React from "react";
import { StyleSheet, Text, View } from "react-native";
import withApollo from "../lib/withApollo";
import { useRouter } from "next/dist/client/router";
import { useRouting } from "expo-next-react-navigation";

const App = () => {
  const { navigate } = useRouting();
  return (
    <View style={styles.container}>
      <Text style={styles.text}>Welcome to Expo + Next.js 👋</Text>
    </View>
  );
};

export default App;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  text: {
    fontSize: 16,
  },
});
```

Did i miss something?

**Comment by emroot** [comment]
Looks like this is happening because I'm using `react ^16.12.0` and `react-dom ^16.12.0`. I'll open a PR.

**Comment by emroot** [comment]
Actually I take that back, it wasn't because, I was using next `9.2` instead of `9.1.5`. Changed it and ti works like a charm.

**Comment by nandorojo** [comment]
Thanks for following up & closing!

**Comment by remyd** [comment]
I'm experiencing the same using using next `9.2.2` and `9.1.5`.

**Comment by nandorojo** [comment]
Could you check if using the latest version (`1.0.2`) solves this?

```sh
yarn add expo-next-react-navigation@v5
```
