### ISSUE TITLE
Link should wrap only string children with <Text> in Link/index.tsx

### ISSUE THREAD

**Issue by kations** [nandorojo/expo-next-react-navigation#13]
Something like:

<TouchableOpacity {...touchableOpacityProps} onPress={nav}>
{typeof children === "string" ? <Text ref={ref} style={style} accessibilityRole="link">
        {children}
</Text> : children}
</TouchableOpacity>

would be great

**Comment by nandorojo** [comment]
Thanks for the issue! I like the idea of supporting children other than text. 

Unfortunately, checking if the child is a string is insufficient, since could can also pass a <Text /> component as a child. 

```
<Link to=“home>Go <Text>home</Text></Link>
```

The above would need to be wrapped in a `Text` component to work, but it would return false for `typeof children === string`.

Perhaps we could add an `isText` prop to `<Link />`, which is default `true`. If set to false, the `Link` would render its children directly, rather than in a `Text` component.

**Comment by kations** [comment]
You are righ. A isText prop should work best 👍

**Comment by nandorojo** [comment]
Published in `0.0.25`, which supports `v4` of React Navigation.

```sh
yarn add expo-next-react-navigation@0.0.25
```

Will try to add it to the `v5` branch soon.

Thanks!

**Comment by nandorojo** [comment]
Still working on adding this to v5, will be done soon.

If someone wants to do it, you just need to: 
1) make a PR for `expo-navigation-core`, edit the `Link/types.ts` file and `index.tsx` file to accept the `isText` prop. [Here is is the way it looks for `v4` support.](https://github.com/nandorojo/expo-next-react-navigation/blob/master/src/components/Link/index.tsx)
2) Edit this library's `Link/index.web.tsx` to do the same.

I can accept a PR, but I'll likely get to it later today or tomorrow.

**Comment by xiCO2k** [comment]
Thanks @nandorojo I have no rush so will wait for your approach on it.

**Comment by nandorojo** [comment]
Thanks to the fast help from @emroot, this request was added to the core library.

I just updated & published the `expo-next-react-navigation` library too (`v1.0.3`). There is now an `isText` prop for the `Link` component now, and it defaults to true.

## Examples
```jsx
// non-text child
<Link isText={false} routeName="home">
  <View />
<Link>
```

```jsx
// text child
<Link routeName="home">
  Go home plz
<Link>
```

```jsx
// text child
<Link routeName="home">
  Go home <Text style={{ fontWeight: 'bold' }}>plzzz</Text>
<Link>
```

## To install

```sh
yarn add expo-next-react-navigation@v5
```

## Request
Could you try out `1.0.3` and let me know here if it works?

**Comment by nandorojo** [comment]
Added to docs https://github.com/nandorojo/expo-next-react-navigation/blob/master/README.md#link

**Comment by xiCO2k** [comment]
Awesome guys, that was super quick.

**Comment by nandorojo** [comment]
Apparently this solution doesn't render an `<a>` on web without the `accessibilityRole="link"`. Anyone know a work-around for that? Can `accessibilityRole` be applied to `TouchableOpacity`?

**Comment by xiCO2k** [comment]
@nandorojo it also renders an `<a>` if you add that prop to a `<View>`:
![image](https://user-images.githubusercontent.com/823088/77704305-afa76100-6fb4-11ea-89e3-83e1b9067a30.png)

**Comment by nandorojo** [comment]
Can it be added to the touchable directly?

**Comment by nandorojo** [comment]
Looks like TouchableOpacity returns a View on web, so it should work:

https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/TouchableOpacity/index.js

**Comment by nandorojo** [comment]
Got it. Will take a look.

**Comment by nandorojo** [comment]
Sorry for the delay on this one. `v5` branch [has fixed this issue](https://github.com/nandorojo/expo-next-react-navigation/commit/90db0469263b4915a15c4e862c4f512e792b9fbd#diff-3c66a00d75897f854d33b9c0714b3cb9) in `v1.0.4`.

```sh
yarn add expo-next-react-navigation@v5
```

**Comment by xiCO2k** [comment]
Thanks man
