### ISSUE TITLE
Missing docs on how to make it work with createSwitchNavigator and nested routes

### ISSUE THREAD

**Issue by alejomendoza** [nandorojo/expo-next-react-navigation#20]
The component `<Link>` doesn't seem to work with nested routes using `createSwitchNavigator`. Also not sure how to implement pages when there are nested routes, seems not easy to just export the component of the screen, what if there is underlying data on the root app like stores, etc...

Check out the implementation here:
https://github.com/skyhitz/mobile/blob/am/include-web-app/modules/marketing/web/NavBar.tsx#L52

Deployment:
https://ui-figibmu4a.now.sh/

**Comment by nandorojo** [comment]
Hey thanks for the issue. Which version of this library / React Navigation are you using?

To clarify, what is the behavior exactly? When you click the link, it doesn’t go to the intended route, on mobile only? Does it work on web?

Are you sure this is related to this library specifically? 

Thanks for the repo example. That said, if you could reproduce the issue in a minimal repository, it would make it much easier for me to figure out what’s up.

**Comment by nandorojo** [comment]
As for your other question, this seems like more of a general app design question related to Next.js routes. Could you make a separate issue and elaborate on that point with a specific use case? Perhaps I can help there.

**Comment by alejomendoza** [comment]
We are using React Navigation `4.0.10`, to repro click on the Log In link at the top right Navbar. The issue is that you will see the route reflected on the path but the app doesn't navigate to that route.

**Comment by nandorojo** [comment]
As I asked before, is the problem on mobile or web? Does it work on web?

**Comment by nandorojo** [comment]
Also, to confirm it's not a problem with this library, you could try this:

```jsx
import { useNavigation } from 'react-navigation-hooks'

export default () => {
  const { navigate } = useNavigation()

  return <Text onPress={() => navigate('SignIn')}>Sign In</Text>
}
```

If this doesn't work, that means it's a problem with the react navigation API and nested routes that doesn't pertain to this library. Could you try that out?

**Comment by nandorojo** [comment]
> Also not sure how to implement pages when there are nested routes, seems not easy to just export the component of the screen, what if there is underlying data on the root app like stores, etc...

@alejomendoza I'm not sure I fully understand the question, but I would recommend checking out `getInitialProps` from next.js (https://nextjs.org/docs/api-reference/data-fetching/getInitialProps). They have a lot of cool ways of loading in data for dynamic pages, if this is what you're looking for.

**Comment by alejomendoza** [comment]
Thanks will try using `react-navigation-hooks` to check if it's a problem with the react navigation API

**Comment by alejomendoza** [comment]
The example you mention above works @nandorojo but when I try this it doesn't:
```
import React from 'react';
import { Text } from 'react-native';
import { useRouting } from 'expo-next-react-navigation';

export default () => {
  const { navigate } = useRouting();

  return (
    <Text
      onPress={() =>
        navigate({ routeName: 'SignIn', web: { path: '/accounts/sign-in' } })
      }
    >
      Sign In
    </Text>
  );
};
```
In my nested routers I have:

```
const RootStackNavigator = createSwitchNavigator(
  {
    AuthLoading: {
      screen: AuthLoadingScreen,
      path: ``,
    },
    App: {
      screen: AppStack,
      path: `app`,
    },
    Auth: {
      screen: AuthStack,
      path: `accounts`,
    },
    WebApp: {
      screen: WebApp,
      path: ``,
    },
  },
  {
    initialRouteName: 'AuthLoading',
  }
);
```
```
const AuthStack = createStackNavigator({
  Accounts: {
    screen: AccountsNavigator,
    navigationOptions: {
      headerShown: false,
    },
    path: ``,
  },
});
```
```
const AccountsNavigator = createStackNavigator({
  AuthScreen: {
    screen: AuthScreen as any,
    navigationOptions: {
      headerShown: false,
      gestureEnabled: false,
    },
    path: `home`,
  },
  SignUp: {
    screen: SignUpScreen as any,
    path: `sign-up`,
  },
  SignIn: {
    screen: SignInScreen as any,
    path: `sign-in`,
  },
  ResetPassword: {
    screen: ResetPasswordScreen as any,
    path: `reset-password`,
  },
  UpdatePassword: {
    screen: UpdatePasswordScreen as any,
    path: `update-password/:token`,
  },
  ConfirmUsernameAndEmail: {
    screen: ConfirmUsernameAndEmailScreen as any,
    path: `confirm-username-and-email`,
  },
});
```

**Comment by nandorojo** [comment]
Got it, thanks for checking. If you can reproduce this in a minimal Expo repo that I can test, I'll clone it and take a look.

**Comment by nandorojo** [comment]
Just checking if you were able to reproduce this issue in a separate repo. If not, let me know and I'll close for now.
