### ISSUE TITLE
Add TypeScript types for React Navigation v5.

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/expo-next-react-navigation#23]
The groundwork for this is already there. Changes needed:

1. In `expo-navigation-core`, add the arguments for `useRouting`'s TypeScript generics.
- Make sure that `getParam` takes in one of the keys as its argument for this route's `params`, and returns that value type.
- Ensure that the `routeName` is a `key` from the `NavigationProp`, and that the `params` match this field as well.

Same goes for this library in `useRouting/index.web.tsx`.

**Comment by Ectsang** [comment]
From https://github.com/nandorojo/expo-next-react-navigation/commit/3a50ff89d2aaa2624048f54696148af3b6a084b9

I ran
`yarn remove expo-next-react-navigation` 
then
`yarn add expo-next-react-nativation@v5`

But when I `expo start` and scan the QR code on my Android, I see
![Screenshot_2020-05-01-19-55-07-358_host exp exponent](https://user-images.githubusercontent.com/1057844/80803747-cfe6c300-8be5-11ea-9d79-039f41d14bc7.jpg)

Is it directly related to this issue?

**Comment by nandorojo** [comment]
It shouldn’t be. This issue is only open as a feature request for the future to remind me to add more TypeScript integrations. Does this also happen on iOS (could you try a simulator if you don’t have one?)

Any shot you could reproduce this in a minimal
repo so I can debug it?

**Comment by nandorojo** [comment]
@Ectsang Could you put your package.json here?

**Comment by nandorojo** [comment]
I made an example using expo-next-react-navigation `1.1.6`, and I'm not seeing the error you mentioned.

**Comment by Ectsang** [comment]
@nandorojo  
It happens on iOS as well (both ios/android device as well as simulators).

my `package.json`

{
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start:web",
    "eject": "expo eject",
    "build": "next build",
    "dev": "next dev -- -p 3344"
  },
  "dependencies": {
    "@expo/next-adapter": "^2.0.0-beta.9",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.5.1",
    "@react-navigation/material-bottom-tabs": "^5.1.10",
    "@react-navigation/native": "^5.1.7",
    "@react-navigation/stack": "^5.2.14",
    "expo": "~36.0.0",
    "expo-next-react-navigation": "^1.1.6",
    "next": "^9.1.5",
    "next-compose-plugins": "^2.2.0",
    "next-fonts": "^0.19.0",
    "next-images": "^1.2.0",
    "next-transpile-modules": "^2.3.1",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-paper": "^3.8.0",
    "react-native-reanimated": "~1.4.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3"
  },
  "devDependencies": {
    "@types/react": "~16.9.0",
    "@types/react-native": "~0.60.23",
    "babel-preset-expo": "~8.0.0",
    "typescript": "~3.6.3"
  },
  "private": true
}

**Comment by nandorojo** [comment]
Could you place code samples, and maybe reproduce this in a repo? Also, any chance you could open a separate issue? It’s actually unrelated to this one.

If you can make a minimal repo that I can look at, it would be much easier for me to help since I can’t recreate this error on my end and don’t know what code is causing it.

**Comment by nandorojo** [comment]
Going to close since I haven't heard back on this.
