### ISSUE TITLE
Will this create standard href for web use?

### ISSUE THREAD

**Issue by shamoons** [nandorojo/expo-next-react-navigation#24]

**Comment by nandorojo** [comment]
I don’t understand the question.

**Comment by shamoons** [comment]
I'm attempting to set up a next.js + expo project so that I can write once and run on web / android / iOS. So if I have a `<Link>`, will it have an `href` attribute?

**Comment by nandorojo** [comment]
Yes, it will create that for you under the hood.

On web, the Link component renders the Link from `next/link` (https://nextjs.org/docs/api-reference/next/link). 

That component from Next passes the href prop down to its first child, which this library creates for you.

**Comment by shamoons** [comment]
Awesome - thank you

**Comment by nandorojo** [comment]
No problem! Feel free to star the library if you end up finding it useful :)
