### ISSUE TITLE
useRouting -- TypeError: Cannot read property 'prefetch' of null

### ISSUE THREAD

**Issue by Ectsang** [nandorojo/expo-next-react-navigation#25]
To reproduce:

# Get the repo
`git clone https://github.com/Ectsang/sample-expo-next-app.git`

# Checkout the branch
`git checkout debug-userouting`

# Install 
`yarn`

# Run on expo web
`yarn web`

## Expected

It should run the web app without errors

## Actual

TypeError: Cannot read property 'prefetch' of null
useRouting
src/hooks/use-routing/index.web.ts:81
  78 |   push: navigate,
  79 |   goBack,
  80 |   popToTop,
> 81 |   prefetch: router.prefetch,
     | ^  82 |   replace,
  83 |   setParams,
  84 | }

**Comment by nandorojo** [comment]
Great, thanks. I’ll take a look.

**Comment by nandorojo** [comment]
Ah, glad you walked me through the steps. You don’t use `yarn web` for Next projects.

Instead, try `yarn next dev`. Make sure to follow the steps from the @expo docs: https://docs.expo.io//guides/using-nextjs

**Comment by Ectsang** [comment]
Yes, I understand we use `yarn next dev` for the nextjs side of things. 

But does this mean I cannot develop expo for mobile re-using the same components?
i.e. do I need to check `Platform.OS === 'web'` to use `useRouting`?

**Comment by nandorojo** [comment]
Nope, you don’t. Under the hood, this library uses `.web.ts` files. If you prefix a file with `.web.js` (or `.native.js`, `.ios.js`, etc), it will use that file for this platform.

This library automatically works across platforms. On mobile, you use react navigation. On web, you use Nextjs. As my read me suggests, I recommend reading about how to create pages in next js. There is also an example repo in the `/examples` folder.

**Comment by nandorojo** [comment]
I’m going to close this for now, but feel follow up if any of that is confusing.

**Comment by oste** [comment]
@nandorojo I was also seeing this issue when running `expo start --web`. It's understood that this is not the intended way to use the library however I find it useful to run expo web alongside next js in order to make sure that I am not breaking existing react-navigation components. I find it better than running the ios/android emulators. I am wondering if maybe we can add a check to see if next is in context and if not it would still fallback to react-navigation.

**Comment by nandorojo** [comment]
@oste interesting idea. How would you check that?

**Comment by oste** [comment]
Will have to ponder that, maybe we can reopen this in the meantime.

**Comment by oste** [comment]
@nandorojo what do you think about setting an env var in next to opt into that functionality https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

adding something like this to .env could then be access with `process.env.NEXT_PUBLIC_EXPO_WEB`

`NEXT_PUBLIC_EXPO_WEB=1`

**Comment by nandorojo** [comment]
I'd have to think about it. You can't conditionally use hooks, and it would be preferable to not edit the entire `useRouting` file just for this. I guess we could just use the `Platform.OS` when exporting.

Re: the `env` approach, we run into the issue of `process.env` not being used in React Native. Maybe this could be achieved using `expo-constants`, though it would introduce a new peer dependency for a feature that isn't really the intended use of the library. I'll give it some thought.

**Comment by oste** [comment]
Couldn't the condition be `process && process.env && process.env.NEXT_PUBLIC_EXPO_WEB` In the case of React Native it would short circuit.

**Comment by oste** [comment]
I see what you mean, we really need the env var to be in React Native. Platform.OS does sound better anyway.
