### ISSUE TITLE
What should my pages/_app.tsx look like to use this?

### ISSUE THREAD

**Issue by shamoons** [nandorojo/expo-next-react-navigation#26]
Currently, I have:
```
function MyApp({ Component, pageProps }: AppProps) {
    const [showBottomNav, setShowBottomNav] = useGlobalState('showBottomNav')
    const [dimensions, setDimensions] = useState<any>(false)

    useLayoutEffect(() => {
        setDimensions(Dimensions.get('screen'))
    }, [])

    Dimensions.addEventListener('change', (d) => setDimensions(d.screen))

    return (
        <PaperProvider theme={customTheme}>
            <Head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            </Head>
            {dimensions &&
                <View style={{
                    flex: 1,
                    top: 0,
                    left: 0,
                    height: dimensions.height,
                    width: '100%',
                    zIndex: 10,
                    position: 'absolute',
                    paddingBottom: 50
                }}>
                    <Component {...pageProps} />
                    {showBottomNav && <FooterBar />}
                </View >
            }
        </PaperProvider >
    )
}

export default MyApp
```

How would I replace this with the `react-navigation` given that I'm using `nextjs` and `expo`

**Comment by nandorojo** [comment]
Hey, thanks for your question! Your `pages/_app.tsx` is a `nextjs` specific file. This wraps every page, only on web. For your mobile app, it does nothing.

> How would I replace this with the react-navigation given that I'm using nextjs and expo

I'm not sure I understand your question. What problem are you having exactly?

While `nextjs` offers `pages/_app.tsx`, React Native offers `App.tsx`. 

Do you want the code in `pages/_app.tsx` to show up in both web and mobile? If so, that isn't exactly part of the scope of this library, but I'm happy to show you a solution if that's what you want to achieve.

---

Also, just some code suggestions – I would change `useLayoutEffect` to `useEffect`, and put `Dimensions.addEventListener('change', (d) => setDimensions(d.screen))` inside the `useEffect` function. You should also remove the listener when the component unmounts, like so: 

```js
useEffect(() => {
  setDimensions(Dimensions.get('screen'))
  const handler = (d) => setDimensions(d.screen)
  Dimensions.addEventListener('change', handler)

  return () => {
    Dimensions.removeEventListener('change', handler)
  }
}, [])

**Comment by shamoons** [comment]
Thanks so much for the insight! What I want is:
(A) to be able to continue to get the SSR benefits of nextjs
(B) have the navigation of React-navigation

Within my _app.tsx, I’m unsure what to do with the Component since that seems to be not react standard. 

I really appreciate you taking the time to help me and by building this great package.

**Comment by nandorojo** [comment]
> What I want is:
(A) to be able to continue to get the SSR benefits of nextjs (B) have the navigation of React-navigation

That is what `expo-next-react-navigation` does for you. All you have to do to make this work is follow the instructions in our readme & see the Expo docs for the Nextjs integration. Then you have to create pages in the pages/ folder for web. Your navigation on mobile can be made normally using react navigation.

Have you seen the example app? https://github.com/nandorojo/expo-next-react-navigation/blob/master/examples/next-nav/App.tsx

> Within my _app.tsx, I’m unsure what to do with the Component since that seems to be not react standard.

I don’t understand what you mean. Is there a problem with your app? What specifically are you trying to achieve that isn’t working? 

`Component` in `pages/_app.tsx` is a Nextjs specific concept. It represents your actual page component. So think of it like this: `pages/_app.tsx` is a wrapper for all pages. `Component` is the page that is being wrapped. Please refer to the Nextjs docs: https://nextjs.org/docs/advanced-features/custom-app

For future reference on open source project issues, I recommend being super explicit about 1) what you expect to happen, 2) what actually happens, and 3) create a minimal repository on Github that the open source maintained can look at that reproduces your issue.

**Comment by shamoons** [comment]
Thanks for your reply. In the sample app, it looks like you don't have a `Component`:
```

  '/': Home,
  Profile,
})

export default createAppContainer(AppNavigator)
```

So then how would I have a layout wrapper for my pages if I don't have a `pages/_app.tsx` to wrap it?

**Comment by nandorojo** [comment]
I recommend implementing a `Layout` component, similar to the way [Gatsby does](https://www.gatsbyjs.org/docs/layout-components/). 

Wrap your `pages/_app.tsx` with your layout component, and do the same with `App.tsx`.
