### ISSUE TITLE
Navigating to a nested navigator

### ISSUE THREAD

**Issue by emroot** [nandorojo/expo-next-react-navigation#27]
`react-navigation` allows you to navigate to a nested navigator using the following api:
`navigation.navigate(route, { screen: SCREEN, ...)`

https://reactnavigation.org/docs/nesting-navigators/

Looks like `useRouting().navigate` only supports one argument `{routeName: ..., params, as:...}`

**Comment by nandorojo** [comment]
Thanks for opening this issue. This lib doesn’t currently support the string as the first argument, but I’m happy to add that / merge a PR that does.

# Steps

1. Edit `useRouting().navigate` in `expo-navigation-core/src/hooks/use-routing` to 1) check if it’s a string, if so, set that as the `routeName`, 2) add an optional `screen` string to the second argument (the same dictionary, with `routeName` omitted). 

- Maybe the `screen` field should be inside a `native` object, similar to the way that the `as` field is in a `web` object. This can help be clear about where the behavior is a no-op.

2. Edit the same file in `expo-next-react-navigation` to make sure that the same API follows on web.

**Comment by nandorojo** [comment]
One issue: the `core` package relies on react navigation `5.0.0-alpha.29`, which doesn’t have a `screen` field. However, upgrading to `5.3.0` leads to some weird TypeScript compilation errors (run `expo-module prepare` after upgrading to see). If there is an easy fix for the TS errors, then it shouldn’t be a problem.

**Comment by nandorojo** [comment]
Going to close this since I haven't heard back, but feel free to let me know if it's still a thing.

**Comment by km-tr** [comment]
@nandorojo 
https://github.com/nandorojo/expo-next-react-navigation/issues/27#issuecomment-626375479

Can I deal with this?
The `expo-next-react-navigation` PR will be published first.

**Comment by km-tr** [comment]
The expo-navigation-core is done.

**Comment by nandorojo** [comment]
It's published at `expo-next-react-navigation@v5`, `1.1.14`
