### ISSUE TITLE
Impossible to setup the project on Win 10

### ISSUE THREAD

**Issue by velidan** [nandorojo/expo-next-react-navigation#32]
Hi nandorojo. Thank you for your work but I can't install your project on Windows 10. Could you, please, help me to solve it?

**Issue reason:** Impossible to set up the project on Win 10 platform.

**Error message:**  **_set -eo pipefail_**.  SyntaxError: Unexpected identifier

**How to reproduce**: 
1) Download the repo as a Zip folder (Win 10 Pro)
2) extract it. Go to the project folder
3) execute in the CMD (bash/win cmd): npm install (yarn)
4) the error appears.

I've attached the screenshot
![expo_next-react-navigationpipefail](https://user-images.githubusercontent.com/9897782/88268297-e2e7cb80-ccda-11ea-8476-e5e0bae18079.jpg)

Thanks for any help!

P.S. You mentioned I can use it without Expo so I'd like to install & use it without it because Expo is forbidden in our project

**Comment by nandorojo** [comment]
Why don't you just run `yarn add expo-next-react-navigation` like the instructions say?

**Comment by velidan** [comment]
I just want to see how the example works

**Comment by nandorojo** [comment]
Got it. Looks like the error is with expo-module scripts. Try changing into the example folder directory and running yarn
