### ISSUE TITLE
Do I need to use nextjs in order to use this router?

### ISSUE THREAD

**Issue by kopax** [nandorojo/expo-next-react-navigation#4]
Helo @nandorojo , and happy new year,

I am not using nextjs, but I think that could be nice to have a router compatible that work with it in case in the futur I want to use it.

Do I need to use nextjs in order to use that router for my expo web and native project?

Best and thanks for sharing!

**Comment by kopax** [comment]
Look at the `src`, the answer is no. I initially tought after reading the `README.md` that this library was another navigation library that was wrapping the best of sub libraries and adding `next.js` capability. In fact it just add `next.js` capability and should be used beside the original one.

**Comment by nandorojo** [comment]
Hey @kopax! This router is simply a wrapper around a React Native app that is using `expo` with the `nextjs` integration. Right now, people tend to use `react-navigation` on React Native apps, but it isn't really optimized for web.

All this library does is integrate `next/router` with `react-navigation` to let you use one API for managing navigation across your entire app. In other words, this package is useful only if you're building an expo/react native app and want help managing your navigation.

Does that help clarify?

**Comment by kopax** [comment]
Yes and thanks you for this. Best!
