### ISSUE TITLE
babel error: Duplicate __self prop found.

### ISSUE THREAD

**Issue by awitherow** [nandorojo/expo-next-react-navigation#47]
You are most likely using the deprecated transform-react-jsx-self Babel plugin. Both __source and __self are automatically set when using the automatic runtime. Please remove transform-react-jsx-source and transform-react-jsx-self from your Babel config.

babel.config.js
```
// @generated: @expo/next-adapter@2.1.5
// Learn more: https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-nextjs.md#shared-steps

module.exports = { presets: ["@expo/next-adapter/babel"] };
```

**Comment by nandorojo** [comment]
Is this a problem with expo's Babel config?

**Comment by nandorojo** [comment]
I haven't seen this error before with this package. Is there something in particular this package is doing that causes an error for you?

**Comment by nandorojo** [comment]
Closing as this is irrelevant.
