### ISSUE TITLE
Reload nested route on web

### ISSUE THREAD

**Issue by GaspardC** [nandorojo/expo-next-react-navigation#64]
Hi, first thanks for your work on expo & rn ! :)

I created a starter repo thanks to expo-next-react-navigation :  [https://github.com/GaspardC/starter-expo-nextjs-react-navigation](https://github.com/GaspardC/starter-expo-nextjs-react-navigation) and it's working well.

I only have a problem when I reload a nested page inside a bottom navigator. Do you know how to keep the bottom tab when the page is reloaded ? 

thanks

<img width="764" alt="Capture d’écran 2021-06-10 à 09 42 39" src="https://user-images.githubusercontent.com/9252579/121485193-41d83100-c9d0-11eb-998a-e95859f38e4c.png">
<img width="764" alt="Capture d’écran 2021-06-10 à 09 42 49" src="https://user-images.githubusercontent.com/9252579/121485198-443a8b00-c9d0-11eb-8887-4dfdeadacdac.png">

**Comment by nandorojo** [comment]
Bottom navigators would only work on native. Web uses exclusively next router. With RN v6, you'll be able to use the bottom tabs UI though

**Comment by GaspardC** [comment]
ok thanks good to know.

I was searching for a workaround, maybe something like reloading the navigator on a nested root.
