### ISSUE TITLE
Can this module be used for bare react native + nextjs too?

### ISSUE THREAD

**Issue by Wuyialex** [nandorojo/expo-next-react-navigation#95]
Looking at the code, there doesn't seem to be any dependency on expo(except dev dependency). Is there any problem if I use it for bare react native + nextjs? But I'm curious as to why the name was named expo-.

**Comment by nandorojo** [comment]
Nope, that should work. I named it that when expo web first came out. It was my first open source project. Naming is hard haha. But I have a new project in the works to totally replace this one (and rename it 😎)
