### ISSUE TITLE
Remix.run integration as alternative to Next?

### ISSUE THREAD

**Issue by algoflows** [nandorojo/expo-next-react-navigation#96]
Hi All,

Amazing work so far, massive fan of this repo!

Just throwing this out there to hear your thoughts, do you think a Remix version could made as an alternative to Nextjs.

Remix being the new SSR framework from the guys who made React Router (Its pretty amazing). 

[www.remix.run](https://remix.run/ ) <----------- pure awesomness coupled with a React Native integration like this.

What do you think, would it be relatively easy to swap Next for Remix and integrate it with React Native Monorepo?

😄

**Comment by nandorojo** [comment]
Definitely intrigued! I'm not working on remix though. Maybe on the (future) docs for this, I could add guidelines for how you could support other frameworks like remix with React Native?

Maybe tamagui from @natew would work with remix for styles?

**Comment by JuniorDEVed** [comment]
That would be great, I would love to get involved.

**Comment by nandorojo** [comment]
Moving to remix repo https://github.com/remix-run/remix/discussions/1578
