### ISSUE TITLE
Any reason not to upgrade to Next 12?

### ISSUE THREAD

**Issue by corysimmons** [nandorojo/expo-next-react-navigation#98]
Noticed 32 dependabot PRs and was just wondering if anything is holding this up from getting Next 12's sweet SWC perf gains. (sorry for being a nuisance)

**Comment by nandorojo** [comment]
nope we’re using Next 12 successfully. It’s only a dev dependency of this package anyway so we don’t install it for you

**Comment by nandorojo** [comment]
i’ll have to look into those PRs

SWC won’t work if you’re using Reanimated FWIW
